### ISSUE TITLE
Exception handling if mqtt server is not reachable

### ISSUE THREAD

**Issue by hbickenbach** [RotorHazard/VRxC-ClearView2#2]
I think this is more a cosmetic issue:

While using the plugin i recognized the following:
If the mqtt server is not reachable, the logfile tracks many expeption errors:

Exception in Heartbeat thread loop
Traceback (most recent call last):
  File "/home/xyz/RotorHazard-4.0.0/src/server/server.py", line 3343, in heartbeat_thread_function
    RaceContext.vrx_manager.updateStatus()
  File "/home/xyz/RotorHazard-4.0.0/src/server/VRxControl.py", line 97, in updateStatus
    controller.updateStatus()
  File "/home/xyz/RotorHazard-4.0.0/src/server/plugins/vrx_cv2/__init__.py", line 118, in updateStatus
    self.get_seat_lock_status()
  File "/home/xyz/RotorHazard-4.0.0/src/server/plugins/vrx_cv2/__init__.py", line 401, in get_seat_lock_status
    seat = self._seat_broadcast
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CV2Controller' object has no attribute '_seat_broadcast'

An informational message is also logged:
MQTT broker not alive at '192.168.188.62'. Waiting 5 seconds...

I think it would be nice, if the exception ist handled by code, if the mqtt server is not connected. Only the "not alive" message should get logged.

**Comment by HazardCreative** [comment]
Agreed, this should be handled better.

**Comment by Ryanf55** [comment]
What's the intended python version for use here? I used `3.8.1` because of these instructions: https://github.com/ryaniftron/clearview_interface_public/blob/master/README.md#install-for-python-library

https://pypi.org/project/monotonic/

`monotonic` is not available past python3.3, but 3.3 is EOL.

https://devguide.python.org/versions/

Tips? 

FYI, I'm developing on Ubuntu 22. If I need to use an older Linux OS, like Ubuntu 20 or 18, just let me know which.

**Comment by HazardCreative** [comment]
monotonic is still available, it's just not really needed past 3.3 and it's only a thin shim now. New development should migrate to time.monotonic.

**Comment by Ryanf55** [comment]
Ok, so what should I do for fixing this bug? Seems the port you did somehow got it running in python2.

**Comment by HazardCreative** [comment]
I'm not sure I understand. RH's minimum version is 3.8 now, there's no need to support less than that.

**Comment by Ryanf55** [comment]
I cannot reproduce this bug, can you (or the original user) please add more information on the environment used to reproduce it? Is there any way to trigger this in software only without having hardware?

When I tried following the README instructions, then manually run `__init__.py`,  I get an import error for monotomic. In theory, running it this way should reproduce the bug if the mqtt server is not on.

```
(.venv) ryan@B650-970:~/Dev/VRxC-ClearView2$ python3 vrx_cv2/__init__.py 
Traceback (most recent call last):
  File "vrx_cv2/__init__.py", line 25, in <module>
    from monotonic import monotonic
ModuleNotFoundError: No module named 'monotonic'
(.venv) ryan@B650-970:~/Dev/VRxC-ClearView2$ python3 --version
Python 3.8.1
(.venv) ryan@B650-970:~/Dev/VRxC-ClearView2$ python3 -m pip install monotomic
Collecting monotomic
  ERROR: Could not find a version that satisfies the requirement monotomic (from versions: none)
ERROR: No matching distribution found for monotomic
WARNING: You are using pip version 19.2.3, however version 23.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(.venv) ryan@B650-970:~/Dev/VRxC-ClearView2$ 

```

**Comment by HazardCreative** [comment]
You have a spelling error here: `pip install monotomic`

**Comment by Ryanf55** [comment]
> pip install monotomic

Copied and pasted.
```
(.venv) ryan@B650-970:~/Dev/VRxC-ClearView2$ pip install monotomic
Collecting monotomic
  ERROR: Could not find a version that satisfies the requirement monotomic (from versions: none)
ERROR: No matching distribution found for monotomic
WARNING: You are using pip version 19.2.3, however version 23.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

In the link I posted above, monotomic is not available on 3.8, so I do not expect this to work.

**Comment by HazardCreative** [comment]
The package is `monotonic`.

**Comment by Ryanf55** [comment]
Ok. Some progress. I need to figure out how to get the relative import happy. Where is `Config` from?
```
$ python3 -m vrx_cv2.__init__
Traceback (most recent call last):
  File "/home/ryan/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/ryan/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/ryan/Dev/VRxC-ClearView2/vrx_cv2/__init__.py", line 27, in <module>
    import Config
ModuleNotFoundError: No module named 'Config'
```

**Comment by HazardCreative** [comment]
It's a RororHazard module that would be available when running as a plugin.

**Comment by Ryanf55** [comment]
> It's a RororHazard module that would be available when running as a plugin.

How do you get the plugin running? 

I followed instructions here (with `main` branch  of RH)
https://github.com/RotorHazard/RotorHazard/blob/v4.0.0/doc/Video%20Receiver.md#software-setup-in-rotorhazard

I copied `config-dist.json` to `config.json` and modified it like so with the VRX params:
```json

{
	"GENERAL": {
		"HTTP_PORT": 5000,
		"ADMIN_USERNAME": "admin",
		"ADMIN_PASSWORD": "rotorhazard",
		"DEBUG": false,
		"CORS_ALLOWED_HOSTS": "*"
	},
	"HARDWARE": {
		"I2C_BUS": 1
	},
	"SENSORS": {
	},
	"SERIAL_PORTS": [],
	"LED": {
		"LED_COUNT": 0,
		"LED_ROWS": 1,
		"LED_GPIO": 10,
		"LED_FREQ_HZ": 800000,
		"LED_DMA": 10,
		"LED_INVERT": false,
		"LED_CHANNEL": 0,
		"PANEL_ROTATE": 0,
		"INVERTED_PANEL_ROWS": false
	},
	"LOGGING": {
		"CONSOLE_LEVEL": "INFO",
		"SYSLOG_LEVEL": "NONE",
		"FILELOG_LEVEL": "INFO",
		"FILELOG_NUM_KEEP": 30,
		"CONSOLE_STREAM": "stdout"
	},
	"VRX_CONTROL": {
            "HOST": "localhost",
            "ENABLED": true
    }
}

```


Then, in logs:
```
(.venv) ryan@B650-970:~/Dev/RotorHazard/src/server$ python server.py 
RotorHazard v4.1.0-dev.1
Release: 4.1.0-dev.1 / Server API: 41 / Latest Node API: 35
Host OS: Linux 6.2.0-35-generic
Python version: 3.8.1
Host machine is 'B650-970' at 192.168.1.111
Loaded plugin module rh_heatgenerator_ladder
Loaded plugin module rh_heatgenerator_standard
Loaded plugin module rh_points_by_position
Loaded plugin module rh_data_export_csv
Loaded plugin module rh_class_rank_best_x_rounds
Plugin module rh_led_handler_bitmap not imported (not supported or may require additional dependencies)
Loaded plugin module rh_connector_trackside
Loaded plugin module rh_led_handler_strip
Plugin module rh_led_handler_character not imported (not supported or may require additional dependencies)
Loaded plugin module rh_class_rank_heat_pos
Loaded plugin module rh_class_rank_cumulative_points
Plugin module rh_led_handler_graph not imported (not supported or may require additional dependencies)
Loaded plugin module rh_data_import_json
Loaded plugin module rh_data_export_json
Loaded plugin module rh_actions_builtin
Using configuration file 'config.json'
Using log file: logs/rh_20231125_170056.log
Loaded module i2c_helper
Unable to create hardware helper 'i2c_helper':  [Errno 13] Permission denied: '/dev/i2c-1'
Loaded module i2c_node
Loaded module serial_node
Using mock hardware interface
Number of nodes found: 8
Loaded module bme280_sensor
Loaded module ina219_sensor
Loaded module linux_sensor
Core temperature available
Set Profile to '1'
Switching to practice mode; races will not be saved until a heat is selected
VRx Control disabled: no registered controllers
Running http server at port 5000
Initializing Trackside connector
Interface: Starting background thread.
^CKeyboardInterrupt
2023-11-26T00:01:00Z
Server terminated by keyboard interrupt
Stopping heartbeat thread
Interface: Stopping background thread

```

Of interest:
```
VRx Control disabled: no registered controllers
```

**Comment by HazardCreative** [comment]
Copy the vrx_cv2 directory into the src/server/plugins directory in your RotorHazard install.
